### ISSUE TITLE
Error in Percentage for Pokemon in Tournament Pages

### ISSUE THREAD

**Issue by VGCPastes** [txfs19260817/falinks-teambuilder#32]
All the Usage Percentage of the Pokemon in the Tournament Pages are inaccurate! We would prefer for them to show percentage of total teams instead of total number of Pokemon.
For example,
Knoxville Regionals > Flutter Mane should be 291/622 = 46.78%, but it is now showing 8.6% _January 2023_
We would also prefer this to also reflect accurately in Top Cut Usage Stats!

**Comment by txfs19260817** [comment]
Hi @VGCPastes , your suggestion makes sense and it was patched right now. Please feel free to reopen it if any further concerns.
